### ISSUE TITLE
Possible error building?

### ISSUE THREAD

**Issue by NoLongerBreathedIn** [Strilanc/Snitch#5]
When I try to build according to instructions, the immediate reply is

> snitch-quantum-surface-code-simulator@0.0.1 build /Users/eyal/Stuff/Snitch
> grunt build-src

Warning: Task "build-src" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! snitch-quantum-surface-code-simulator@0.0.1 build: `grunt build-src`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the snitch-quantum-surface-code-simulator@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

???

**Comment by Strilanc** [comment]
Try `grunt build-debug`.

The install instructions were copy-pasted from Quirk but became invalid during development. (This project is in a half-developed state.)

**Comment by NoLongerBreathedIn** [comment]
Right, there's an easy fix here. One-line change in GruntFile.js.

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Snitch/commit/35512624903fbcc6c1e6d4af86253017a66b0f0f

Thanks for pointing this out! Sorry for the delay.
